newland.mappingPath=classpath:mapper/*/*.xml
newland.testSwitch=ON

# Single file max size
newland.ftp.multipart.maxFileSize=100Mb
# All files max size
newland.ftp.multipart.maxRequestSize=100Mb

#ftp use
newland.ftpServer = 121.4.123.73
newland.ftpPort = 6069
newland.ftpUserName = hcftp
newland.ftpUserPassword = 123456
newland.ftpPath = hc/