newland.auth.wechat.sessionHost=https://api.weixin.qq.com/sns/jscode2session
newland.auth.wechat.appId=wxf83d66b0e9f5964d
newland.auth.wechat.secret=cc
newland.auth.wechat.grantType=authorization_code
newland.auth.wechat.key=key
newland.auth.wechat.mchId=mchId
newland.auth.wechat.wxPayUnifiedOrder=https://api.mch.weixin.qq.com/pay/unifiedorder
newland.auth.wechat.wxNotifyUrl=http://www.vipwuye.com/app/payment/notify
newland.auth.wechat.rentingNotifyUrl=http://www.vipwuye.com/app/payment/rentingNotify
newland.auth.wechat.goodsNotifyUrl=http://www.vipwuye.com/goods/notify
newland.auth.wechat.oweFeeNotifyUrl=http://www.vipwuye.com/app/payment/oweFeeNotify
newland.auth.wechat.tempCarFeeNotifyUrl=http://www.vipwuye.com/app/payment/tempCarFeeNotifyUrl

# 公众号信息
newland.auth.wechat.wechatAppId=key
newland.auth.wechat.wechatAppSecret=mchId


